# Generated by Django 6.1 on 2026-09-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_assign_orphan_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('transfer', 'Transfer')], default='visit', max_length=10),
        ),
    ]
